2018-12-4 update New feature and improvement * Enable VK_EXT_scalar_block_layout extension * Enable VK_KHR_swapchain_mutable_format extension * Enable on-chip GSVS ring on GFX9, seeing up to 10% performance gain * Add dccBitsPerPixelThreshold setting * Re-enable tracing of missing registers in thread trace * Remove some useless settings
Issue fix
* Undefined reference to vk::OverrideDispatchTable_ND(vk::DispatchTable*)
* Errors with multiple monitors and direct display
* dEQP-VK.api.device_init.create_instance_device_intentional_alloc_fail test failure
* Crash issue on Raven caused by the implementation of VK_AMD_memory_overallocation_behavior extension
* dEQP-VK.glsl.atomic_operations.*_*signed64bit_* failure on gfx7
* ELEX crash with Steam Proton
* CopyTextureRegion failure when copying a MSAA Resource in D32_FLOAT or D16_UNORM to a R32_UINT format
* GFX9: CB_DCC_CONTROL register is programmed incorrectly
* Perf counter instance incorrect calculation